"use client";
import { useMemo, useState } from "react";

type Product={id:number;name:string;category:string;price:number;image:string;note:string};
const media=(id:string,ext="png")=>`https://static.wixstatic.com/media/${id}~mv2.${ext}`;
const products:Product[]=[
 [1,"The Majestic Sapphire & Diamond Bracelet","Bracelets",61463,"c34d0c9a9ede484c930c24b55b5120a7","Royal sapphires framed by brilliant diamonds."],
 [2,"The Chroma Sapphire Step-Cut Bracelet","Bracelets",43800,"c4d06624f67443619dd0faf0424915bc","Architectural step-cut sapphires with a diamond finish."],
 [3,"The Riviera Turquoise & Diamond Pendant","Necklaces",12500,"e1ec92ff91264099be1f24c48750ea01","Luminous turquoise encircled by white diamonds."],
 [4,"The Royal Blue Sapphire Heart Pendant","Necklaces",14200,"a1a9996e59cf4344a22ba1d417957cc1","A romantic sapphire heart made for meaningful gifting."],
 [5,"The Kaleidoscope Sapphire Huggies Earrings","Earrings",8200,"9585d8217db24fc8983fc35a4e921f2d","Colourful sapphire huggies with everyday polish."],
 [6,"The Sculpted Pavé Signet Diamond Ring","Rings",9800,"de1cb1a1418a4deea86c89b7e1161dfb","A contemporary signet covered in pavé brilliance."],
 [7,"The Grand Oval Pavé Signet Diamond Ring","Rings",11600,"028503aa1d774bdfa6dab8cc078f5e22","A bold oval signet balanced with delicate pavé work."],
 [8,"The Imperial Pavé Dome Cluster Ring","Rings",13400,"5698004dffdf4c1386f3405e23d5e4af","A sculptural dome set with a field of bright diamonds."],
 [9,"Graduated Oval & Round Diamond Bracelet","Bracelets",38200,"a738f523ca6b4d0f8b796dd21f7d7ded","Graduated diamond cuts create fluid movement and light."],
 [10,"Diamond Floral Pear Marquise Link Bracelet","Bracelets",32600,"342b8a3ae5204cf3b058a86d480fd94e","Pear and marquise diamonds arranged as delicate flowers."],
 [11,"The Eclipse Two-Tone Pear Tennis Bracelet","Bracelets",28750,"3045094fec0b42e0bf30d818193f2582","A two-tone tennis bracelet with pear-cut accents."],
 [12,"The Romantic Heart Halo Diamond Pendant","Necklaces",7450,"5f453cb3d43b4c718d2f5b892f198fbe","A classic heart surrounded by a fine diamond halo."],
].map(([id,name,category,price,img,note])=>({id,name,category,price,image:media(`b4a9a1_${img}`),note})) as Product[];
const money=(n:number)=>new Intl.NumberFormat("en-AE",{style:"currency",currency:"AED",maximumFractionDigits:0}).format(n);

export default function Home(){
 const [category,setCategory]=useState("All Products"),[query,setQuery]=useState(""),[cart,setCart]=useState<Product[]>([]),[active,setActive]=useState<Product|null>(null),[cartOpen,setCartOpen]=useState(false),[checkout,setCheckout]=useState(false),[menu,setMenu]=useState(false);
 const filtered=useMemo(()=>products.filter(p=>(category==="All Products"||p.category===category)&&p.name.toLowerCase().includes(query.toLowerCase())),[category,query]);
 const total=cart.reduce((s,p)=>s+p.price,0),go=(id:string)=>{document.getElementById(id)?.scrollIntoView({behavior:"smooth"});setMenu(false)},add=(p:Product)=>{setCart(c=>[...c,p]);setActive(null);setCartOpen(true)};
 const cats=[["Sets","73756ae1baa8450eb9b795ac37103f2f"],["Rings","53d0d0a796da491894d129beff03d449"],["Earrings","9b29b717d4374d039aed84bc2b3c33fe"],["Bracelets","1bf3e9dec13448b48a3d4eb5b672f6de"],["Necklaces","5f0bba1f699e47ecbbb47102b92c5dc2"]];
 return <main>
  <div className="announcement">Complimentary delivery across the UAE</div>
  <header><button className="menu" onClick={()=>setMenu(!menu)} aria-label="Menu">☰</button><a className="brand" href="/"><img src={media("e6636e_6ccb162994df4e7f814ffbb4f51f5be5")} alt="DIA Jewels"/></a><nav className={menu?"open":""}><a href="/">Home</a><a href="/shop">Shop</a><a href="/about">About Us</a><a href="/customization">Customization</a><a href="/contact">Contact</a></nav><div className="actions"><label>⌕<input value={query} onChange={e=>{setQuery(e.target.value);go("shop")}} placeholder="Search"/></label><button onClick={()=>setCartOpen(true)}>Bag <b>{cart.length}</b></button></div></header>
  <section id="home" className="hero"><img src={media("b4a9a1_a4c750b65be34922962cd2c4a384474c","jpg")} alt="Fine diamond jewellery"/><div className="shade"/><div className="heroCopy"><small>DIA JEWELS • DUBAI</small><h1>Your Destination<br/>for Timeless Elegance</h1><a className="heroButton" href="/shop">Discover the collection</a></div></section>
  <section className="intro"><p>Every diamond tells a story — yours should be unforgettable.</p><h2>We design timeless pieces that capture emotion, commitment, and individuality, crafted to be worn today and treasured forever.</h2></section>
  <section className="section editorial"><Title over="Elegance Collections" main="Discover our collections"/><div className="editorialGrid">{[["Forever Beginnings","144b5ac41b0240a3a020b7a8f337eed0"],["Statement Pieces","5e925aa51c1c47aa8f3be8a7121b193a"],["Everyday Radiance","b53f4b6b46a04ba09502b084f1137af7"],["Moments & Memories","66c650c37c7040f9baf50543b0191fcb"]].map(([t,id])=><button key={t} onClick={()=>go("shop")}><img src={media(`b4a9a1_${id}`,"jpg")} alt={t}/><span>{t}</span></button>)}</div></section>
  <section id="shop" className="section shop"><Title over="Signature Brilliance" main="Shop fine jewellery"/><div className="filters">{["All Products","Rings","Earrings","Bracelets","Necklaces"].map(c=><button className={category===c?"selected":""} onClick={()=>setCategory(c)} key={c}>{c}</button>)}</div><div className="productGrid">{filtered.map(p=><article key={p.id}><button className="pic" onClick={()=>setActive(p)}><img src={p.image} alt={p.name}/><span>Quick view</span></button><button className="productName" onClick={()=>setActive(p)}>{p.name}</button><p>{money(p.price)}</p><button className="add" onClick={()=>add(p)}>Add to cart</button></article>)}</div></section>
  <section className="categoryStrip">{cats.map(([t,id])=><button key={t} onClick={()=>{setCategory(t==="Sets"?"All Products":t);go("shop")}}><img src={media(`b4a9a1_${id}`,"jpeg")} alt={t}/><span>{t}</span></button>)}</section>
  <section id="custom" className="split"><img src={media("b4a9a1_592ceb1af89849bda7e34fe5263772ba","jpg")} alt="Custom jewellery craftsmanship"/><div><small>Bespoke by DIA</small><h2>Made just for you</h2><p>Your story deserves a one-of-a-kind design. From sketch to sparkle, our artisans handcraft every diamond piece to reflect your personal style and celebrate life’s special moments.</p><a href="https://api.whatsapp.com/send/?phone=%2B97142659268&text=Hi%2C+I%27d+like+to+create+a+custom+piece" target="_blank">Create a custom design</a></div></section>
  <section id="story" className="split story"><div><small>Our Brand</small><h2>Elegance meets exceptional craftsmanship</h2><p>In the heart of Dubai’s Gold & Diamond Park, DIA Jewels creates certified fine jewellery with care, artistry and authenticity. Each piece is thoughtfully crafted to embody sophistication and grace.</p></div><img src={media("b4a9a1_fc361419580b438daec6cde8b7ff6ddd","jpg")} alt="DIA Jewels design"/></section>
  <section className="advantages"><h2>DIA Jewels Advantages</h2><div>{[["◇","International Certification","Every diamond is certified for quality and authenticity."],["✦","Free UAE Shipping","Complimentary delivery with luxury packaging."],["↻","7-Day Exchange","An easy exchange service for peace of mind."],["✎","Custom Designs","Create a piece that is entirely your own."],["⌁","Trusted Since 2012","Over a decade of fine diamond craftsmanship."]].map(([i,t,d])=><article key={t}><b>{i}</b><h3>{t}</h3><p>{d}</p></article>)}</div></section>
  <section id="contact" className="contact"><div><small>Visit us</small><h2>Gold & Diamond Park, Dubai</h2><p>Discover the collections in person and meet our jewellery specialists.</p></div><div><a href="tel:+97142659268">+971 4 265 9268</a><a href="https://www.instagram.com/diajewelsdubai/" target="_blank">@diajewelsdubai</a><a href="https://api.whatsapp.com/send/?phone=%2B97142659268" target="_blank">Chat on WhatsApp</a></div></section>
  <footer><img src={media("e6636e_6ccb162994df4e7f814ffbb4f51f5be5")} alt="DIA Jewels"/><p>Fine diamond jewellery & custom engagement rings</p><div>{[["Shop All","shop"],["Our Story","story"],["Our Craft","custom"],["Contact Us","contact"]].map(([t,id])=><button key={id} onClick={()=>go(id)}>{t}</button>)}</div><small>© DIA JEWELS FZCO • DUBAI, UAE</small></footer>
  {active&&<Overlay close={()=>setActive(null)}><div className="productModal"><button className="close" onClick={()=>setActive(null)}>×</button><img src={active.image} alt={active.name}/><div><small>{active.category}</small><h2>{active.name}</h2><h3>{money(active.price)}</h3><p>{active.note}</p><ul><li>Certified fine jewellery</li><li>Luxury DIA packaging</li><li>Complimentary UAE delivery</li></ul><button className="dark" onClick={()=>add(active)}>Add to cart</button></div></div></Overlay>}
  {cartOpen&&<Overlay close={()=>setCartOpen(false)} drawer><aside className="cart"><div className="cartHead"><h2>Your Bag</h2><button onClick={()=>setCartOpen(false)}>×</button></div>{cart.length===0?<div className="empty"><p>Your bag is empty.</p><button onClick={()=>{setCartOpen(false);go("shop")}}>Explore jewellery</button></div>:<><div className="cartItems">{cart.map((p,i)=><div className="cartItem" key={`${p.id}-${i}`}><img src={p.image} alt=""/><div><p>{p.name}</p><b>{money(p.price)}</b><button onClick={()=>setCart(c=>c.filter((_,x)=>x!==i))}>Remove</button></div></div>)}</div><div className="cartTotal"><p><span>Subtotal</span><b>{money(total)}</b></p><small>Shipping calculated at checkout</small><button className="dark" onClick={()=>{setCartOpen(false);setCheckout(true)}}>Checkout</button></div></>}</aside></Overlay>}
  {checkout&&<Overlay close={()=>setCheckout(false)}><div className="checkout"><button className="close" onClick={()=>setCheckout(false)}>×</button><div><small>Secure checkout</small><h2>Complete your order</h2><p>Your DIA jewellery will arrive in signature luxury packaging.</p></div><form onSubmit={e=>{e.preventDefault();alert("Checkout is ready for DIA’s payment gateway connection.")}}><div className="row"><label>First name<input required/></label><label>Last name<input required/></label></div><label>Email<input type="email" required/></label><label>Phone<input type="tel" required/></label><label>Delivery address<textarea required rows={3}/></label><div className="summary"><span>Total</span><b>{money(total)}</b></div><button className="dark">Continue to payment</button><small>Payment gateway connection required before live transactions.</small></form></div></Overlay>}
 </main>
}
function Title({over,main}:{over:string;main:string}){return <div className="title"><small>{over}</small><h2>{main}</h2></div>}
function Overlay({children,close,drawer=false}:{children:React.ReactNode;close:()=>void;drawer?:boolean}){return <div className={drawer?"overlay drawer":"overlay"}><button className="backdrop" onClick={close} aria-label="Close"/>{children}</div>}
